# Generated by Django 4.0.3 on 2022-03-08 08:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('category', models.CharField(choices=[('ML', 'Meals'), ('DK', 'Drinks'), ('DS', 'Desserts')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
