# Generated by Django 4.0.3 on 2022-03-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeinfo',
            name='logo',
            field=models.ImageField(blank=True, default='logo/tfcafe_logo.png', upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/products/product-placeholder.png', upload_to='products/'),
        ),
    ]
