# Generated by Django 4.0.3 on 2022-03-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_cafeinfo_gallery_testimonials_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
