# Generated by Django 4.0.3 on 2022-03-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
