# Generated by Django 4.0.3 on 2022-04-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_remove_gallery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('announcement', models.TextField()),
                ('table_accomodation', models.TextField()),
                ('delivery_info', models.TextField()),
            ],
        ),
    ]
