# Generated by Django 4.0.3 on 2022-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_testimonial_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeinfo',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cafeinfo',
            name='schedule',
            field=models.TextField(),
        ),
    ]
