# Generated by Django 4.0.3 on 2022-04-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(null=1, on_delete=django.db.models.deletion.SET_NULL, related_name='featured', to='cafe.product')),
            ],
        ),
    ]
