# Generated by Django 4.0.3 on 2022-05-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_featuredproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='product_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.product'),
        ),
        migrations.CreateModel(
            name='FeaturedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.testimonial')),
            ],
        ),
    ]
