# Generated by Django 4.0.3 on 2022-03-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_alter_cafeinfo_location_alter_cafeinfo_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AlterField(
            model_name='cafeinfo',
            name='logo',
            field=models.ImageField(blank=True, default='tfcafe_logo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('meal', 'Meals'), ('drink', 'Drinks'), ('dessert', 'Desserts')], max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
