# Generated by Django 4.0.3 on 2022-05-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_alter_featuredproduct_product_id_featuredreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RenameField(
            model_name='cafeinfo',
            old_name='about',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='cafeinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='cafeinfo',
            name='announcement',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='cafeinfo',
            name='delivery_info',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='cafeinfo',
            name='table_accomodation',
            field=models.TextField(default='nothing'),
        ),
    ]
