# Generated by Django 4.0.3 on 2022-03-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_alter_product_options_alter_cafeinfo_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafeinfo',
            old_name='socials',
            new_name='facebook',
        ),
    ]
