# Generated by Django 4.0.3 on 2022-05-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_delete_about_rename_about_cafeinfo_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeinfo',
            name='table_accomodation',
        ),
        migrations.AddField(
            model_name='cafeinfo',
            name='table_accommodation',
            field=models.TextField(default='We can accommodate up to 14 tables.'),
        ),
        migrations.AlterField(
            model_name='cafeinfo',
            name='announcement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cafeinfo',
            name='delivery_info',
            field=models.TextField(),
        ),
    ]
