# Generated by Django 4.0.3 on 2022-03-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_rename_socials_cafeinfo_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeinfo',
            name='logo',
            field=models.ImageField(blank=True, default='logo/default-logo.png', upload_to='logo/'),
        ),
    ]
