# Generated by Django 4.0.3 on 2022-05-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_remove_cafeinfo_table_accomodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeinfo',
            name='table_accommodation',
            field=models.TextField(),
        ),
    ]
