# Generated by Django 4.0.3 on 2022-05-23 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_alter_cafeinfo_table_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 9, 54, 51, 361850, tzinfo=utc)),
        ),
    ]
