# Generated by Django 4.0.3 on 2022-05-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_gallery_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
